### ISSUE TITLE
Is multicore or GPU acceleration supported?

### ISSUE THREAD

**Issue by dalhoomist** [audreyqyfu/mrpc#2]
HI,

I am exploring the potential of using your package for some very large data. Is there any GPU acceleration option? Or multicore support?

**Comment by audreyqyfu** [comment]
Thanks for your interest in our package.  Our method performs sequential hypothesis testing, and the alpha level for later tests depends on the results from earlier tests.  This means that the process has to be run on one processor.  

Can MRPC be run directly on GPU?  I'm not sure at this point.  If you manage to run it on GPU, please let us know!

Audrey

**Comment by dalhoomist** [comment]
Thank you very much for your response.
